### ISSUE TITLE
simple_form: 'klass' for nil:NilClass

### ISSUE THREAD

**Issue by HendrikRoth** [ryanb/nested_form#165]
Same issue as [#135](https://github.com/ryanb/nested_form/issues/135)

undefined method `klass' for nil:NilClass

i'm using the git version. rails 3.1

**Comment by joeleba** [comment]
```
= simple_nested_form_for @marque do |f|
  = f.input :name
  = f.input :published
  = f.input :image

  = f.submit

  = f.link_to_add "Add", :cars

  = f.simple_fields_for :cars do |nf|
    = nf.input :name
    = nf.input :published
```
I'm having problem with link_to_add when I try to put it before `f.simple_fields_for` like in the above snippet. The error message is:
```
ActionView::Template::Error (undefined method `klass' for nil:NilClass):
```

Must `link_to_add` always be after `simple_fields_for`? Thank you!
