### ISSUE TITLE
'is not focusable' error in Chrome when submitting a form with an unfilled, but removed, input field.

### ISSUE THREAD

**Issue by ghost** [ryanb/nested_form#262]
The error occurs in the following scenario:
- An input field has a 'required' attribute
- That input field has a link_to_remove that is supposed to remove the field
- The user removes the field and submits the form

**ERROR:** In Chrome, the following error occurs as Chrome tries to show the user where the required field is that is required to submit the form:

`An invalid form control with name='foo[bar][1368040373416][baz]' is not focusable.`

**The fix**: When a input element is removed, the 'required' attribute should be removed so the form can be properly submitted.

**Comment by yormanjos1980** [comment]
ddd

**Comment by yormanjos1980** [comment]
dddd
