### ISSUE TITLE
Multiple add fields due to turbolinks on Rails 4

### ISSUE THREAD

**Issue by tohyongcheng** [ryanb/nested_form#286]
After navigating through a few pages, the form adds more than 1 field into the nested form. It is mostly due to turbolinks on Rails 4.

More information on how to solve it may be here: https://github.com/kossnocorp/jquery.turbolinks

I have tried it, but its not working with this gem. We may need to edit the js of the nested_form gem.

**Comment by raldred** [comment]
Is there anyway to improve nested form to support turbolinks properly?
I always put javascript after all content to improve page load performance.
https://developer.yahoo.com/performance/rules.html#js_bottom

**Comment by amnesia7** [comment]
If the script is in the body and evaluated every time then changing the bottom of the nested_form.js file to be the following seems to work:
```js
  window.nestedFormEvents = new NestedFormEvents();
  // Setup click handlers
  $(document)
    .on('click', 'form a.add_nested_fields',    nestedFormEvents.addFields)
    .on('click', 'form a.remove_nested_fields', nestedFormEvents.removeFields);
  // Tidy up click handlers
  $(document).on('page:after-remove', function () {
    $(document)
      .off('click', 'form a.add_nested_fields',    nestedFormEvents.addFields)
      .off('click', 'form a.remove_nested_fields', nestedFormEvents.removeFields);
  });
})(jQuery);
```
