### ISSUE TITLE
How to add fields programaticaly?

### ISSUE THREAD

**Issue by USvER** [ryanb/nested_form#329]
I want to add nested form fields using javascript and populate it with data... How to do this?

I need to generate dom from blueprint, and then using jquery replace some values... But i don't know how...

**Comment by svensson-david** [comment]
There's a good starting point added to the wiki for anyone looking for this
https://github.com/ryanb/nested_form/wiki/How-To:-Add-fields-with-pre-defined-values

**Comment by USvER** [comment]
@svensson-david yeah, that is what i did... Added event listener and change value from there...
